### ISSUE TITLE
What does the error code 5570 mean?

### ISSUE THREAD

**Issue by jpb2251** [pigsyn/MacProFirmwareToolUpdate#3]
I have a 2009 Mac Pro 4,1, and I wanted to upgrade the firmware.  I downloaded the tool.  I disabled the SIP.  When I ran the tool, I received back the error code 5570.  What did I do wrong?  What does the error code 5570 mean?

mac pro 4,1
Quad-core Intel Xeon 2.66
2 processors
8 cores
Boot ROM version MP41.081.808
GPU ATI Radeon HD 4870

**Comment by jpb2251** [comment]
I am sorry.  I did not follow the directions regarding firmware package.  Your tool works great.  I just can't follow instructions.  Thank you.

**Comment by pigsyn** [comment]
Error 5570 means one of the dmg didn't get downloaded and patching script is failing.
Did you manage to upgrade ?

**Comment by jpb2251** [comment]
Thank you for making the tool. You are right. I failed to download the
firmware.  Once I did, it worked. Thanks.

**Comment by MBarrie53** [comment]
I am also hitting this issue. I don't understand how to fix it. 
Any help would be great. I downloaded the tool and am running it. 
I also downloaded MacProEFIUpdate.dmg as described in this tutorial 
https://www.ifixit.com/Guide/How+to+Upgrade+the+Firmware+of+a+2009+Mac+Pro+41/98985

**Comment by pigsyn** [comment]
Hello

Did you manage to solve your issue ? If not please provide your MacOS
version and exact error on the github issue
https://github.com/pigsyn/MacProFirmwareToolUpdate/issues/3

Regards


Le jeu. 19 sept. 2019 à 02:01, MBarrie53 <notifications@github.com> a
écrit :

**Comment by MBarrie53** [comment]
Hello,

Thank you so much for getting back to me. I didn't realize at first that I
need to open and mount the MacProEFIUpdate.dmg. I re read the ifixit
article and noticed I had missed that step.

Thank you,
Matthew

**Comment by SEIZMICdesign** [comment]
running through the steps here and I get the message: 

"This software is not supported on your system."

I'm on an early '09 4,1. I ran the csrutil disable which told me it was successful. Sort of at a dead end as far as I can tell. Anyone else run into this?

**Comment by pigsyn** [comment]
Opened new issue https://github.com/pigsyn/MacProFirmwareToolUpdate/issues/4
