### ISSUE TITLE
10.13.6 & Weird Graphics Freeze ?

### ISSUE THREAD

**Issue by furbies** [pigsyn/MacProFirmwareToolUpdate#7]
So. I updated the firmware as per your tool (thanks for that) and installed High Sierra, but now, sometimes (most of the time) I find the UI freezes, but the audio keeps playing. Sometimes part(s) of the screens are also corrupted/garbled.

Is this a known issue ?

is there a workaround ? (apart from not playing video)

tia

Pete...

  Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	Quad-Core Intel Xeon
  Processor Speed:	2.66 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	MP51.0084.B00
  SMC Version (system):	1.39f5
  SMC Version (processor tray):	1.39f5

**Comment by pigsyn** [comment]
Hello, this is not a known issue, what graphic card are you using in your Mac Pro ?
High Sierra might have removed support for older cards.

**Comment by furbies** [comment]
> Hello, this is not a known issue, what graphic card are you using in your Mac Pro ?
> High Sierra might have removed support for older cards.

Mine is a stock 2009 Mac Pro Quad 2.66 w/ NVIDIA GeForce GT 120 (GPU)

The problem only seems to happen when I'm playing video, and then only some times.

I haven't noticed a pattern yet that might help me narrow it down further.

So I thought I'd ask, just in case someone here might have encountered a similar issue ?

regards

pete...
